export const enMessages = {
  layout: {
    appTitle: 'Athli Landing Page',
    appDescription: 'Generated by create next app',
  },
  home: {
    authenticatedContent: 'Authenticated content',
  },
  sidebar: {
    group: {
      general: 'General',
    },
    links: {
      dashboard: 'Dashboard',
      marketing: 'Marketing',
      messaging: 'Messages',
      workouts: 'Workouts',
      athletes: 'Athletes',
      calendar: 'Calendar',
    },
    theme: {
      lightMode: 'Light mode',
      darkMode: 'Dark mode',
      toggleAria: 'Toggle theme',
    },
    language: {
      label: 'English',
      aria: 'Change language (current: English)',
    },
    settings: {
      label: 'Settings',
    },
  },
  greetings: {
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
  },
} as const;

export type EnMessages = typeof enMessages;
