export const enMessages = {
  layout: {
    appTitle: 'Clerk Next.js Quickstart',
    appDescription: 'Generated by create next app',
  },
  home: {
    authenticatedContent: 'Authenticated content',
  },
} as const

export type EnMessages = typeof enMessages


