export const enMessages = {
  layout: {
    appTitle: 'Clerk Next.js Quickstart',
    appDescription: 'Generated by create next app',
  },
  home: {
    authenticatedContent: 'Authenticated content',
  },
  sidebar: {
    group: {
      general: 'General',
    },
    links: {
      dashboard: 'Dashboard',
      marketing: 'Marketing',
      messaging: 'Messaging',
      workouts: 'Workouts',
      athletes: 'Athletes',
      calendar: 'Calendar',
    },
    theme: {
      lightMode: 'Light mode',
      darkMode: 'Dark mode',
      toggleAria: 'Toggle theme',
    },
    language: {
      label: 'English',
      aria: 'Change language (current: English)',
    },
    settings: {
      label: 'Settings',
    },
  },
} as const

export type EnMessages = typeof enMessages


