/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/edit-language`; params?: Router.UnknownInputParams; } | { pathname: `/edit-units`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-home` | `/athlete-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-performance` | `/athlete-performance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-settings` | `/athlete-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-calendar` | `/coach-calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-clients` | `/coach-clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-inbox` | `/coach-inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-settings` | `/coach-settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/edit-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-language`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-units`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/athlete-home` | `/athlete-home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/athlete-performance` | `/athlete-performance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/athlete-settings` | `/athlete-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coach-calendar` | `/coach-calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coach-clients` | `/coach-clients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coach-inbox` | `/coach-inbox`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coach-settings` | `/coach-settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/edit-color-scheme${`?${string}` | `#${string}` | ''}` | `/edit-language${`?${string}` | `#${string}` | ''}` | `/edit-units${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/athlete-home${`?${string}` | `#${string}` | ''}` | `/athlete-home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/athlete-performance${`?${string}` | `#${string}` | ''}` | `/athlete-performance${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/athlete-settings${`?${string}` | `#${string}` | ''}` | `/athlete-settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coach-calendar${`?${string}` | `#${string}` | ''}` | `/coach-calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coach-clients${`?${string}` | `#${string}` | ''}` | `/coach-clients${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coach-inbox${`?${string}` | `#${string}` | ''}` | `/coach-inbox${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coach-settings${`?${string}` | `#${string}` | ''}` | `/coach-settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/edit-language`; params?: Router.UnknownInputParams; } | { pathname: `/edit-units`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-home` | `/athlete-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-performance` | `/athlete-performance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athlete-settings` | `/athlete-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-calendar` | `/coach-calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-clients` | `/coach-clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-inbox` | `/coach-inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach-settings` | `/coach-settings`; params?: Router.UnknownInputParams; };
    }
  }
}
