import type { Client } from '@/services/client-service';

/**
 * Mock clients data for development
 * TODO: This will be replaced by TanStack Query when backend is integrated
 * Usage: const { data: clients, isLoading } = useClients()
 */
export const MOCK_CLIENTS: Partial<Client>[] = [
    {
        id: '1',
        firstName: 'John',
        lastName: 'Smith',
        name: 'John Smith',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces',
        age: 32,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'john.smith@example.com',
        phone: '+1 (555) 123-4567',
        country: 'United States',
    },
    {
        id: '2',
        firstName: 'Sarah',
        lastName: 'Johnson',
        name: 'Sarah Johnson',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=faces',
        age: 28,
        // gender: 'female',
        coachingType: 'online',
        email: 'sarah.johnson@example.com',
        phone: '+1 (555) 234-5678',
        country: 'Canada',
    },
    {
        id: '3',
        firstName: 'Mike',
        lastName: 'Wilson',
        name: 'Mike Wilson',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=faces',
        age: 35,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'mike.wilson@example.com',
        phone: '+44 20 7946 0958',
        country: 'United Kingdom',
    },
    {
        id: '4',
        firstName: 'Emily',
        lastName: 'Davis',
        name: 'Emily Davis',
        avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=faces',
        age: 29,
        // gender: 'female',
        coachingType: 'online',
        email: 'emily.davis@example.com',
        phone: '+1 (555) 345-6789',
        country: 'United States',
    },
    {
        id: '5',
        firstName: 'David',
        lastName: 'Brown',
        name: 'David Brown',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=faces',
        age: 41,
        // gender: 'male',
        coachingType: 'hybrid',
        email: 'david.brown@example.com',
        phone: '+61 2 9374 4000',
        country: 'Australia',
    },
    {
        id: '6',
        firstName: 'Lisa',
        lastName: 'Anderson',
        name: 'Lisa Anderson',
        avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=faces',
        age: 26,
        // gender: 'female',
        coachingType: 'online',
        email: 'lisa.anderson@example.com',
        phone: '+1 (555) 456-7890',
        country: 'United States',
    },
    {
        id: '7',
        firstName: 'Chris',
        lastName: 'Martinez',
        name: 'Chris Martinez',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=faces',
        age: 38,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'chris.martinez@example.com',
        phone: '+34 91 123 4567',
        country: 'Spain',
    },
    {
        id: '8',
        firstName: 'Jessica',
        lastName: 'Taylor',
        name: 'Jessica Taylor',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=faces',
        age: 31,
        // gender: 'female',
        coachingType: 'online',
        email: 'jessica.taylor@example.com',
        phone: '+1 (555) 567-8901',
        country: 'Canada',
    },
    {
        id: '9',
        firstName: 'Robert',
        lastName: 'Lee',
        name: 'Robert Lee',
        avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200&h=200&fit=crop&crop=faces',
        age: 34,
        // gender: 'male',
        coachingType: 'hybrid',
        email: 'robert.lee@example.com',
        phone: '+1 (555) 678-9012',
        country: 'United States',
    },
    {
        id: '10',
        firstName: 'Amanda',
        lastName: 'White',
        name: 'Amanda White',
        avatarUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=faces',
        age: 27,
        // gender: 'female',
        coachingType: 'online',
        email: 'amanda.white@example.com',
        phone: '+44 20 7946 0959',
        country: 'United Kingdom',
    },
    {
        id: '11',
        firstName: 'Michael',
        lastName: 'Chen',
        name: 'Michael Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=200&h=200&fit=crop&crop=faces',
        age: 30,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'michael.chen@example.com',
        phone: '+86 10 1234 5678',
        country: 'China',
    },
    {
        id: '12',
        firstName: 'Sophie',
        lastName: 'Martin',
        name: 'Sophie Martin',
        avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=faces',
        age: 25,
        // gender: 'female',
        coachingType: 'online',
        email: 'sophie.martin@example.com',
        phone: '+33 1 23 45 67 89',
        country: 'France',
    },
    {
        id: '13',
        firstName: 'James',
        lastName: 'Thompson',
        name: 'James Thompson',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=faces',
        age: 39,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'james.thompson@example.com',
        phone: '+1 (555) 789-0123',
        country: 'United States',
    },
    {
        id: '14',
        firstName: 'Emma',
        lastName: 'Garcia',
        name: 'Emma Garcia',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop&crop=faces',
        age: 28,
        // gender: 'female',
        coachingType: 'hybrid',
        email: 'emma.garcia@example.com',
        phone: '+34 91 234 5678',
        country: 'Spain',
    },
    {
        id: '15',
        firstName: 'Daniel',
        lastName: 'Rodriguez',
        name: 'Daniel Rodriguez',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces',
        age: 33,
        // gender: 'male',
        coachingType: 'in-person',
        email: 'daniel.rodriguez@example.com',
        phone: '+1 (555) 890-1234',
        country: 'United States',
    },
];
